
var robustaData = {
	
	"projectData": {
		"name": "Orcamento",
		"date": "13/07/16 20h20min7s BRT",
		"loc": "49695",
		"trynumber": "308",
		"catchnumber": "370",
		"finallynumber": "2"
	},
	
	"allBadSmellData": [
	
		{	"packageName": 	"src/br.com.hslife.orcamento.aspect", 
			"codeLink":	"#/Orcamento/src/br/com/hslife/orcamento/aspect/AuditoriaAspect.java#156#", 
			"className": 	"AuditoriaAspect.java",
			"methodName": 	"afterUpdate",
			"line":		"156",
			"smellType":	"Dummy Handler"
		},
		{	"packageName": 	"src/br.com.hslife.orcamento.entity", 
			"codeLink":	"#/Orcamento/src/br/com/hslife/orcamento/entity/EntityPersistence.java#126#", 
			"className": 	"EntityPersistence.java",
			"methodName": 	"getFieldValues",
			"line":		"126",
			"smellType":	"Dummy Handler"
		},
		{	"packageName": 	"src/br.com.hslife.orcamento.service", 
			"codeLink":	"#/Orcamento/src/br/com/hslife/orcamento/service/ImportacaoLancamentoService.java#681#", 
			"className": 	"ImportacaoLancamentoService.java",
			"methodName": 	"processarArquivoCSVImportado",
			"line":		"681",
			"smellType":	"Careless Cleanup"
		},
		{	"packageName": 	"src/br.com.hslife.orcamento.service", 
			"codeLink":	"#/Orcamento/src/br/com/hslife/orcamento/service/ImportacaoLancamentoService.java#680#", 
			"className": 	"ImportacaoLancamentoService.java",
			"methodName": 	"processarArquivoCSVImportado",
			"line":		"680",
			"smellType":	"Exception Thrown From Finally Block"
		},
		{	"packageName": 	"src/br.com.hslife.orcamento.service", 
			"codeLink":	"#/Orcamento/src/br/com/hslife/orcamento/service/ImportacaoLancamentoService.java#681#", 
			"className": 	"ImportacaoLancamentoService.java",
			"methodName": 	"processarArquivoCSVImportado",
			"line":		"681",
			"smellType":	"Exception Thrown From Finally Block"
		},
		{	"packageName": 	"src/br.com.hslife.orcamento.task", 
			"codeLink":	"#/Orcamento/src/br/com/hslife/orcamento/task/AgendamentoTask.java#130#", 
			"className": 	"AgendamentoTask.java",
			"methodName": 	"enviarEmailNotificacao",
			"line":		"130",
			"smellType":	"Dummy Handler"
		},
		{	"packageName": 	"src/br.com.hslife.orcamento.util", 
			"codeLink":	"#/Orcamento/src/br/com/hslife/orcamento/util/DetalheLancamentoComparator.java#64#", 
			"className": 	"DetalheLancamentoComparator.java",
			"methodName": 	"compare",
			"line":		"64",
			"smellType":	"Dummy Handler"
		},
		{	"packageName": 	"src/br.com.hslife.orcamento.util", 
			"codeLink":	"#/Orcamento/src/br/com/hslife/orcamento/util/ItemDespensaComparator.java#68#", 
			"className": 	"ItemDespensaComparator.java",
			"methodName": 	"compare",
			"line":		"68",
			"smellType":	"Dummy Handler"
		},
		{	"packageName": 	"src/br.com.hslife.orcamento.util", 
			"codeLink":	"#/Orcamento/src/br/com/hslife/orcamento/util/LancamentoContaComparator.java#64#", 
			"className": 	"LancamentoContaComparator.java",
			"methodName": 	"compare",
			"line":		"64",
			"smellType":	"Dummy Handler"
		},
		{	"packageName": 	"src/br.com.hslife.orcamento.util", 
			"codeLink":	"#/Orcamento/src/br/com/hslife/orcamento/util/LancamentoImportadoComparator.java#64#", 
			"className": 	"LancamentoImportadoComparator.java",
			"methodName": 	"compare",
			"line":		"64",
			"smellType":	"Dummy Handler"
		},
		{	"packageName": 	"src/br.com.hslife.orcamento.util", 
			"codeLink":	"#/Orcamento/src/br/com/hslife/orcamento/util/DetalheFaturaComparator.java#64#", 
			"className": 	"DetalheFaturaComparator.java",
			"methodName": 	"compare",
			"line":		"64",
			"smellType":	"Dummy Handler"
		},
		{	"packageName": 	"src/br.com.hslife.orcamento.util", 
			"codeLink":	"#/Orcamento/src/br/com/hslife/orcamento/util/EntityLabelComparator.java#64#", 
			"className": 	"EntityLabelComparator.java",
			"methodName": 	"compare",
			"line":		"64",
			"smellType":	"Dummy Handler"
		},
		{	"packageName": 	"src/br.com.hslife.orcamento.util", 
			"codeLink":	"#/Orcamento/src/br/com/hslife/orcamento/util/Util.java#83#", 
			"className": 	"Util.java",
			"methodName": 	"MD5",
			"line":		"83",
			"smellType":	"Dummy Handler"
		},
		{	"packageName": 	"src/br.com.hslife.orcamento.util", 
			"codeLink":	"#/Orcamento/src/br/com/hslife/orcamento/util/Util.java#96#", 
			"className": 	"Util.java",
			"methodName": 	"SHA1",
			"line":		"96",
			"smellType":	"Dummy Handler"
		},
		{	"packageName": 	"src/br.com.hslife.orcamento.util", 
			"codeLink":	"#/Orcamento/src/br/com/hslife/orcamento/util/Util.java#110#", 
			"className": 	"Util.java",
			"methodName": 	"SHA256",
			"line":		"110",
			"smellType":	"Dummy Handler"
		},
		{	"packageName": 	"src/br.com.hslife.orcamento.util", 
			"codeLink":	"#/Orcamento/src/br/com/hslife/orcamento/util/Util.java#112#", 
			"className": 	"Util.java",
			"methodName": 	"SHA256",
			"line":		"112",
			"smellType":	"Dummy Handler"
		},
		{	"packageName": 	"src/br.com.hslife.orcamento.util", 
			"codeLink":	"#/Orcamento/src/br/com/hslife/orcamento/util/DetalheOrcamentoComparator.java#64#", 
			"className": 	"DetalheOrcamentoComparator.java",
			"methodName": 	"compare",
			"line":		"64",
			"smellType":	"Dummy Handler"
		}
	]
,
	
	"allPackageData": [
		
		[
			"0",
			"src/br.com.hslife.orcamento.aspect",
			"197",
			"0",
			"1",
			"0",
			"0",
			"0",
			"0",
			"1"	
		],
		[
			"4",
			"src/br.com.hslife.orcamento.entity",
			"9335",
			"0",
			"1",
			"0",
			"0",
			"0",
			"0",
			"1"	
		],
		[
			"12",
			"src/br.com.hslife.orcamento.service",
			"6277",
			"0",
			"0",
			"0",
			"0",
			"1",
			"2",
			"3"	
		],
		[
			"13",
			"src/br.com.hslife.orcamento.task",
			"193",
			"0",
			"1",
			"0",
			"0",
			"0",
			"0",
			"1"	
		],
		[
			"14",
			"src/br.com.hslife.orcamento.util",
			"2157",
			"0",
			"11",
			"0",
			"0",
			"0",
			"0",
			"11"	
		],
		[
			"1",
			"src/br.com.hslife.orcamento.component",
			"1553",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"2",
			"src/br.com.hslife.orcamento.controller",
			"12892",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"3",
			"src/br.com.hslife.orcamento.converter",
			"343",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"5",
			"src/br.com.hslife.orcamento.enumeration",
			"1782",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"6",
			"src/br.com.hslife.orcamento.exception",
			"380",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"7",
			"src/br.com.hslife.orcamento.facade",
			"2260",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"8",
			"src/br.com.hslife.orcamento.listener",
			"99",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"9",
			"src/br.com.hslife.orcamento.model",
			"1896",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"10",
			"src/br.com.hslife.orcamento.repository",
			"4273",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"11",
			"src/br.com.hslife.orcamento.security",
			"79",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"15",
			"src/br.com.hslife.orcamento.validator",
			"74",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"16",
			"test/br.com.hslife.orcamento.component",
			"268",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"17",
			"test/br.com.hslife.orcamento.entity",
			"1923",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"18",
			"test/br.com.hslife.orcamento.json",
			"133",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"19",
			"test/br.com.hslife.orcamento.repository",
			"1538",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"20",
			"test/br.com.hslife.orcamento.service",
			"1533",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"21",
			"test/br.com.hslife.orcamento.util",
			"502",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"22",
			"test/lib",
			"8",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		]
	]
,
	
	"badSmellTypeDensity": [
		{"type": "Empty Catch Block", "count": "0"},
		{"type": "Dummy Handler", "count": "14"},
		{"type": "Unprotected Main Program", "count": "0"},
		{"type": "Nested Try Statement", "count": "0"},
		{"type": "Careless Cleanup", "count": "1"},
		{"type": "Exception Thrown From Finally Block", "count": "2"}
	]

}
