server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/orcamento
    username: orcamento
    password: d1nh31r0
    driverClassName: org.mariadb.jdbc.Driver